/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package raja.cs665.hw3;

import raja.cs665.hw3.enumTypes.AccountType;
import raja.cs665.hw3.enumTypes.BankName;
import raja.cs665.hw3.enumTypes.CustomerType;
import raja.cs665.hw3.exceptions.BankException;

import java.text.ParseException;
import java.util.Date;
import java.text.DateFormat;

public class App {

    public static void main(String[] args) throws ParseException {
        System.out.println("\n--Testing Basic version of Accounts--");
        AccountFactory bankApp = new AccountFactory(BankName.Basic);

        String bobId = "011-11-1111";
        bankApp.createCustomer("Bob", bobId, getDate("June 12, 2021"));
        bankApp.createAccount(AccountType.Checking, bobId,
                "01-011",  getDate("June 12, 2021"), 1200);

        String aliceId = "011-11-1111";
        bankApp.createCustomer("Alice", aliceId, getDate("June 1, 2022"));
        bankApp.createAccount(AccountType.Savings, aliceId,
                "01-001",  getDate("June 1, 2022"), 1000);

        System.out.println("\n--Testing Bank of America version of Accounts--");
//        Bank of America
        AccountFactory boaBank = new AccountFactory(BankName.BOA);
        boaBank.createCustomer("Bob", bobId, getDate("June 12, 2021"));
        boaBank.createAccount(AccountType.Checking, bobId,
                "01-011",  getDate("June 12, 2021"), 1200);

        boaBank.createCustomer("Alice", aliceId, getDate("June 1, 2022"));
        boaBank.createAccount(AccountType.Savings, aliceId,
                "01-001",  getDate("June 1, 2022"), 1000);

        //Chase bank
        System.out.println("\n--Testing Chase version of Accounts--");
        AccountFactory chaseBank = new AccountFactory(BankName.Chase);
        chaseBank.createCustomer("Bob", bobId, getDate("June 12, 2021"));
        chaseBank.createAccount(AccountType.Checking, bobId,
                "01-011",  getDate("June 12, 2021"), 1200);

        chaseBank.createCustomer("Alice", aliceId, getDate("June 1, 2022"));
        chaseBank.createAccount(AccountType.Savings, aliceId,
                "01-001",  getDate("June 1, 2022"), 1000);


        // Part 2
        System.out.println("\n--Testing Bank of America version of UI--");

        BankUIFactory boaUI = new BankUIFactory(BankName.BOA);
        boaUI.createUI();

        System.out.println("\n--Testing Chase version of UI--");
        BankUIFactory chaseUI = new BankUIFactory(BankName.Chase);
        chaseUI.createUI();


        //part 3
        // using simple factory
        String charlieId = "033-33-3333";
        System.out.println("\nPart3 First version using SimpleFactory");
        StandardFactoryCustomer sfCustomer = new StandardFactoryCustomer();
        sfCustomer.createCustomer(CustomerType.Standard, "Bob", bobId, getDate("June 1, 2021"));
        sfCustomer.createCustomer(CustomerType.Preferred, "Alice", aliceId, getDate("June 12, 2022"));
        sfCustomer.createCustomer(CustomerType.Business, "Charlie", charlieId, getDate("May 22, 2022"));

        // using  factory method
        System.out.println("\nPart3 Second version using FactoryMethod");
        CustomerFactory customerFactoryStandard = new CustomerFactory(CustomerType.Standard);
        customerFactoryStandard.createCustomer("Bob", bobId, getDate("June 1, 2021"));
        CustomerFactory customerFactoryPref = new CustomerFactory(CustomerType.Preferred);
        customerFactoryPref.createCustomer("Alice", aliceId, getDate("June 12, 2022"));
        CustomerFactory customerFactoryBusiness = new CustomerFactory(CustomerType.Business);
        customerFactoryBusiness.createCustomer("Charlie", charlieId, getDate("May 22, 2022"));












//        bankApp.createCustomer("Bob", bobId, getDate("June 1, 2022"));

//        bankApp.createTransaction(TransactionType.Deposit, getDate("June 3, 2022"),
//                200, aliceId,  "01-001", null);

//        bankApp.setJointOwner("01-001", "011-11-1111", "022-22-2222",
//                getDate("June 6, 2022"));

//        bankApp.createTransaction(TransactionType.Withdraw, getDate("June 7, 2022"),
//                2000, bobId, "01-001", null);

//        String charlieId = "033-33-3333";


//        bankApp.createCustomer("Charlie", charlieId,
//                getDate("June 7, 2022"));
//
//        bankApp.createAccount(charlieId, AccountType.Savings,
//                "02-001",  getDate("June 7, 2022"), 3000);
//
//        bankApp.setJointOwner("02-001", charlieId, bobId,
//                getDate("June 7, 2022"));


//        bankApp.printStatement("022-22-2222", getDate("June 8, 2022"));

//        bankApp.createTransaction(TransactionType.Deposit, getDate("June 9, 2022"),
//                100, bobId, "01-001", null);
//
//
//        bankApp.createTransaction(TransactionType.Transfer, getDate("June 9, 2022"),
//                700, bobId,  "02-001", "01-001");
//
//        bankApp.createTransaction(TransactionType.Withdraw, getDate("June 10, 2022"),
//                2000, bobId, "01-001", null);


//        bankApp.printStatement("011-11-1111", getDate("June 15, 2022"));

//        bankApp.printStatement("033-33-3333", getDate("June 15, 2022"));

    }

    private static Date getDate(String dateStr) {
        try {
            return DateFormat.getDateInstance().parse(dateStr);
        } catch (ParseException e) {
            throw new BankException("Invalid Date... " + e.getMessage());
        }

    }
}
